//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace CodeAbility.MonitorAndCommand.Windows8Monitor.MessageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageServiceReference.IMessageService")]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/StoreMessage", ReplyAction="http://tempuri.org/IMessageService/StoreMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeAbility.MonitorAndCommand.Models.ContentTypes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeAbility.MonitorAndCommand.Models.Message[]))]
        System.Threading.Tasks.Task StoreMessageAsync(CodeAbility.MonitorAndCommand.Models.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/ListLastMessages", ReplyAction="http://tempuri.org/IMessageService/ListLastMessagesResponse")]
        System.Threading.Tasks.Task<CodeAbility.MonitorAndCommand.Models.Message[]> ListLastMessagesAsync(int numberOfMessages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/ListDeviceLastMessages", ReplyAction="http://tempuri.org/IMessageService/ListDeviceLastMessagesResponse")]
        System.Threading.Tasks.Task<CodeAbility.MonitorAndCommand.Models.Message[]> ListDeviceLastMessagesAsync(int numberOfMessages, string deviceName, string objectName, string parameterName, int rowInterval);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : CodeAbility.MonitorAndCommand.Windows8Monitor.MessageServiceReference.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<CodeAbility.MonitorAndCommand.Windows8Monitor.MessageServiceReference.IMessageService>, CodeAbility.MonitorAndCommand.Windows8Monitor.MessageServiceReference.IMessageService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MessageServiceClient() : 
                base(MessageServiceClient.GetDefaultBinding(), MessageServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMessageService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MessageServiceClient.GetBindingForEndpoint(endpointConfiguration), MessageServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MessageServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MessageServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task StoreMessageAsync(CodeAbility.MonitorAndCommand.Models.Message message) {
            return base.Channel.StoreMessageAsync(message);
        }
        
        public System.Threading.Tasks.Task<CodeAbility.MonitorAndCommand.Models.Message[]> ListLastMessagesAsync(int numberOfMessages) {
            return base.Channel.ListLastMessagesAsync(numberOfMessages);
        }
        
        public System.Threading.Tasks.Task<CodeAbility.MonitorAndCommand.Models.Message[]> ListDeviceLastMessagesAsync(int numberOfMessages, string deviceName, string objectName, string parameterName, int rowInterval) {
            return base.Channel.ListDeviceLastMessagesAsync(numberOfMessages, deviceName, objectName, parameterName, rowInterval);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMessageService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMessageService)) {
                return new System.ServiceModel.EndpointAddress("http://monitorandcommand.azurewebsites.net/MessageService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return MessageServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMessageService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return MessageServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMessageService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IMessageService,
        }
    }
}
