//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAbility.MonitorAndCommand.Server.MessageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageServiceReference.IMessageService")]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/StoreMessage", ReplyAction="http://tempuri.org/IMessageService/StoreMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeAbility.MonitorAndCommand.Models.ContentTypes))]
        void StoreMessage(CodeAbility.MonitorAndCommand.Models.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/StoreMessage", ReplyAction="http://tempuri.org/IMessageService/StoreMessageResponse")]
        System.Threading.Tasks.Task StoreMessageAsync(CodeAbility.MonitorAndCommand.Models.Message message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : CodeAbility.MonitorAndCommand.Server.MessageServiceReference.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<CodeAbility.MonitorAndCommand.Server.MessageServiceReference.IMessageService>, CodeAbility.MonitorAndCommand.Server.MessageServiceReference.IMessageService {
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StoreMessage(CodeAbility.MonitorAndCommand.Models.Message message) {
            base.Channel.StoreMessage(message);
        }
        
        public System.Threading.Tasks.Task StoreMessageAsync(CodeAbility.MonitorAndCommand.Models.Message message) {
            return base.Channel.StoreMessageAsync(message);
        }
    }
}
